/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.MagazineController;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Magazine;
import validation.Validation;

/**
 *
 * @author ADMIN
 */
public class MagazineView extends javax.swing.JFrame {
    MagazineController mazController = new MagazineController();
    Vector<String> header = new Vector<>();
    Vector data = new Vector();
    Validation validation = new Validation();

    /**
     * Creates new form MagazineView
     */
    public MagazineView() {
        initComponents();
        header.add("Magazine ID");
        header.add("Title");
        header.add("Publisher");
        header.add("Price");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pButton = new javax.swing.JPanel();
        pInput = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPublisher = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        pBtn = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnViewAll = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        pTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMaz = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Magazine");
        setPreferredSize(new java.awt.Dimension(600, 300));

        pButton.setLayout(new java.awt.GridLayout(2, 1, 0, 20));

        pInput.setToolTipText("");
        pInput.setLayout(new java.awt.GridLayout(2, 4, 20, 20));

        jLabel1.setText("Magazine ID:");
        pInput.add(jLabel1);

        txtID.setPreferredSize(new java.awt.Dimension(50, 20));
        pInput.add(txtID);

        jLabel2.setText("Title:");
        pInput.add(jLabel2);

        txtTitle.setPreferredSize(new java.awt.Dimension(150, 20));
        pInput.add(txtTitle);

        jLabel3.setText("Publiser:");
        pInput.add(jLabel3);

        txtPublisher.setPreferredSize(new java.awt.Dimension(100, 20));
        pInput.add(txtPublisher);

        jLabel4.setText("Price");
        pInput.add(jLabel4);

        txtPrice.setMinimumSize(new java.awt.Dimension(50, 20));
        txtPrice.setPreferredSize(new java.awt.Dimension(50, 20));
        pInput.add(txtPrice);

        pButton.add(pInput);

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 20);
        flowLayout1.setAlignOnBaseline(true);
        pBtn.setLayout(flowLayout1);

        btnStart.setText("Start Server");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        pBtn.add(btnStart);

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        pBtn.add(btnNew);

        btnViewAll.setText("View All");
        btnViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllActionPerformed(evt);
            }
        });
        pBtn.add(btnViewAll);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        pBtn.add(btnExit);

        pButton.add(pBtn);

        getContentPane().add(pButton, java.awt.BorderLayout.PAGE_END);

        pTable.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Magazine Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 153, 153))); // NOI18N
        pTable.setLayout(new java.awt.GridLayout(1, 0));

        tableMaz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Magazine ID", "Title", "Publisher", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableMaz);
        if (tableMaz.getColumnModel().getColumnCount() > 0) {
            tableMaz.getColumnModel().getColumn(0).setPreferredWidth(30);
            tableMaz.getColumnModel().getColumn(1).setPreferredWidth(150);
            tableMaz.getColumnModel().getColumn(2).setPreferredWidth(120);
            tableMaz.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        pTable.add(jScrollPane1);

        getContentPane().add(pTable, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        if (validation.checkEmptyInput(txtID) && validation.checkEmptyInput(txtTitle)
                && validation.checkEmptyInput(txtPublisher) && validation.checkEmptyInput(txtPrice)) {
            if (validation.checkIDInput(txtID)) {
                String mazID = this.txtID.getText();
                String title = this.txtTitle.getText();
                String publisher = this.txtPublisher.getText();
                double price = Double.parseDouble(this.txtPrice.getText());
                
                Magazine magazine = mazController.getMagazine(mazID);
                if (magazine == null) {
                    int n = mazController.newMagazine(mazID, title, publisher, price);
                    if (n == 1)
                        getAll();
                    else
                        JOptionPane.showMessageDialog(this, "Add magazine failure!");
                } else
                    JOptionPane.showMessageDialog(this, "Duplicate key!");
            }
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllActionPerformed
        // TODO add your handling code here:
        getAll();
    }//GEN-LAST:event_btnViewAllActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnStartActionPerformed

    private void getAll() {
        data = mazController.getAll();
        
        DefaultTableModel tblModel;
        tblModel = (DefaultTableModel) this.tableMaz.getModel();
        tblModel.setDataVector(data, header);
        
        jScrollPane1.setViewportView(tableMaz);
        if (tableMaz.getColumnModel().getColumnCount() > 0) {
            tableMaz.getColumnModel().getColumn(0).setPreferredWidth(30);
            tableMaz.getColumnModel().getColumn(1).setPreferredWidth(150);
            tableMaz.getColumnModel().getColumn(2).setPreferredWidth(120);
            tableMaz.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        pTable.add(jScrollPane1);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MagazineView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MagazineView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MagazineView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MagazineView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MagazineView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnViewAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pBtn;
    private javax.swing.JPanel pButton;
    private javax.swing.JPanel pInput;
    private javax.swing.JPanel pTable;
    private javax.swing.JTable tableMaz;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtPublisher;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
